# Module: CoreVarEntorno
# Document : modules\CoreVarEntorno\config.yml
#
# @author: Sergio PÃ©rez <sergio.perez@albatronic.com>
# @copyright: INFORMATICA ALBATRONIC SL
# @date 28.08.2012 20:59:40
#
---
CoreVariables:
  includesHead:
    twigCss: _global/css.html.twig
    twigJs: _global/js.html.twig
  login_required: YES
  permission_control: YES
